language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: r1X8BoU83eHiA83UXLii6r+yxvARWfRtLurikNt5iZ2t8Ul52U2hLZijwl0itAbImdN3+XWGq3BRc9kjPngoA5tL/w5de4uFm+fh6F88V0i3alMXrGZ/gNFuescMIxSBlUGEHMWr7dr934QNXPMzqwmssAwMkm/8Hn3XZnbqy+x3dvMWTOFsRnj+k89uJWAS3ifnnj0tJKYs1l4FPXX5+/ZsURfVdwn6SAEC/c+ivrrmWQtAoBkEIkhnMHLXy8qhAS6p+FyTPJnud1sePK/qGmya/+eabQFo4G6vwV7ikCYrod2bLDAQcvhOgBE44G5bbb6PtH0vbl929EXLs7cx5Qk3LwdYeXsBxgq47KXfBhpAljYRCs8R1iuK9dCv7Xrhygr77wuIbUlRWtw17Qx9xaQTttMpi4ijKhovf4GDo+TKpKE+Yvu4qTo3bMCunMwbU29mC1PqUv4IpjSYsY8pain0T4TMhFwukM2sM9dZ6LIDjG/CzFuqZ5Du7B0Ho+c62S9ZO6+Y3KoTlsV8/qDTyh+gMNAy0Iyy4f2WZregx7n+h/SoNCnx9bCAThBm31yrL6eXz7zXSms0mjQHJCjL8jrktDIAJps4/mYk99COPgZG/Js94ZL/ecmOSY5SCMKAAJea5pKecUIInXRnwj2vUDSo1CzpdxV+xmIA9Jca1F8=
